### ISSUE TITLE
How to see round robin fixture 

### ISSUE THREAD

**Issue by interludic** [princemaple/tourny#5]
https://tourny.pages.dev/tournaments/ed12b126-8cd9-49e1-a4a7-45e086ef9469/setup

![Screenshot_20240212-141234](https://github.com/princemaple/tourny/assets/6327261/360197d2-34f0-42ed-9c73-92ebf64f00fa)
Cannot use schedule, seems to reset.

Unsure how to apply round robin schedule and export.

H

**Comment by princemaple** [comment]
![image](https://github.com/princemaple/tourny/assets/1329716/3c0ba37e-c863-4c1b-bd9e-7f1be4416c1e)
There is a separate `Add Rule` button for inclusion and exclusion.

**Comment by princemaple** [comment]
![image](https://github.com/princemaple/tourny/assets/1329716/df41f604-d653-48e5-8c55-f16114b6c9d5)
